name: hommie
description: "Will be added in the future"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ^3.35.1

# Define riverpod version to use across all riverpod packages
riverpod_version: &riverpod_version 3.0.0-dev.17

dependencies:
  battery_plus: ^6.2.3
  computer:
    git:
      url: https://github.com/seftoner/computer.git
  connectivity_plus: ^6.1.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: *riverpod_version
  flutter_secure_storage: ^9.2.4
  flutter_web_auth_2: ^4.1.0
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0
  go_router: ^16.2.0
  hooks_riverpod: *riverpod_version
  http: ^1.2.2
  json_annotation: ^4.9.0
  logger: ^2.6.1
  multicast_dns: ^0.3.3
  network_info_plus: ^6.1.4
  oauth2: ^2.0.3
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  riverpod: *riverpod_version
  riverpod_annotation: *riverpod_version
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  web_socket_channel: ^3.0.1
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: main
      path: workmanager/
  drag_arrange:
    git:
      url: https://github.com/seftoner/drag_arrange.git
  isar_community: ^3.2.0-dev.2
  isar_community_flutter_libs: ^3.2.0-dev.2

dev_dependencies:
  bdd_widget_test: ^2.0.0
  build_runner: ^2.7.0
  custom_lint: ^0.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  go_router_builder: ^3.3.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  patrol: ^3.19.0
  patrol_finders: ^2.9.0
  riverpod_generator: *riverpod_version
  riverpod_lint: *riverpod_version
  isar_community_generator:
    git:
      url: https://github.com/callumw-k/isar-community
      ref: migrating-to-source_gen-3
      path: packages/isar_community_generator/

flutter:
  uses-material-design: true

patrol:
  app_name: hommie
  android:
    package_name: com.seftoner.hommie
  ios:
    bundle_id: com.seftoner.hommie
  macos:
    bundle_id: com.seftoner.hommie
