name: hommie
description: "Will be added in the future"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ^3.27.1

dependencies:
  battery_plus: ^6.2.1
  computer:
    git:
      url: https://github.com/seftoner/computer.git
  connectivity_plus: ^6.1.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.0
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_web_auth_2: ^4.0.2
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  go_router: ^16.2.4
  hooks_riverpod: ^2.4.9
  http: ^1.3.0
  json_annotation: ^4.8.1
  logger: ^2.2.0
  multicast_dns: ^0.3.2+7
  network_info_plus: ^6.1.3
  oauth2: ^2.0.3
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  riverpod_annotation: ^2.6.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  web_socket_channel: ^3.0.2
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: main
      path: workmanager/

dev_dependencies:
  bdd_widget_test: ^1.8.1
  build_runner: 2.4.14
  custom_lint: ^0.7.3
  
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  go_router_builder: ^2.8.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mockito: ^5.4.5
  patrol: ^3.14.0
  patrol_finders: ^2.6.0
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

patrol:
  app_name: hommie
  android:
    package_name: com.seftoner.hommie
  ios:
    bundle_id: com.seftoner.hommie
  macos:
    bundle_id: com.seftoner.hommie
