name: computer
version: 3.3.0
description: Easy to use pool of concurrent workers with compute() like API.

environment:
  sdk: ">=3.9.0 <4.0.0"
resolution: workspace

dev_dependencies:
  test: ^1.25.15
  lints: ^6.0.0
