name: drag_arrange
description: A Flutter package for creating reorderable staggered grid views.
version: 0.0.3
repository: https://github.com/seftoner/drag_arrange.git

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: 0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
